### ISSUE TITLE
Support embedded folders

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#121]
Embedded folders, such as the following, are not supported currently:

``` yaml
services:
     A:
         folders:
            foo: 'foo'
            bar: 'bar'
     B:
         folders:
            foo: 'foo'
            bar: 'foo/bar'
```
