### ISSUE TITLE
Error with incomplete setup

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#133]
This setup is not parsed correctly, but no error is logged:

``` yaml
name: empty_conf

folders:

services:

```
