### ISSUE TITLE
Flickr: Handle dynamic album creation

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#144]
In Flickr, a folder's path is used as an album name. This is fine, but we could also handle another scenario. If folder doesn't have a path, photos should be sent to the photostream, and new directories should create an album.
Nested directories should not create an album.

For example:

``` yaml
flickr:
    driver: flickr
    folders:
        my_album: my-album
        photos:
```

This setup should create the album `my-album`. Then, any photo in the `photos` folder should be sent to the Photostream, unless if it's in a directory. A directory should create an album.

```
test.jpg # -> sent to the photostream
foobar/ # -> new album
    spam.jpg # -> in the foobar album
    eggs.jpg # -> in the foobar album
    lol/
        toto.jpg # -> in the foobar album, as lol/toto.jpg
```
